version: '3.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.0.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  mongo:
    image: mongo
    env_file: config.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "testing"
      MONGO_INITDB_ROOT_PASSWORD: "testing"
    ports:
      - '27017:27017'
    volumes:
     - ./scripts/:/docker-entrypoint-initdb.d

  messagebroker:
    image: rabbitmq:3
    ports:
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"

networks:
  default:
    external:
      name: trogsNetwork
